version: "3.5"
services:
  nginx:
    image: nginx:1.20
   # working_dir: /www
    ports:
      - 80:80
      # Add the port for Xdebug here
      - 9003:9003
    environment:
      PHP_IDE_CONFIG: "serverName=Docker"
    volumes:
      - ./www:/www
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./log/nginx:/var/log/nginx/
    networks:
      - invoices_network

  php:
    build: ./docker/php
    working_dir: /www
    ports:
      - 9000:9000
    volumes:
      - ./www:/www
      - ./log/back:/usr/local/var/log
    networks:
      - invoices_network

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./db:/var/lib/mysql/
    networks:
      - invoices_network

networks:
  invoices_network:
    ipam:
      driver: default
      config:
        - subnet: 192.168.100.0/24
